name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: dani251/tex-pdf-builder
  LATEST_FROM: full

jobs:
  build-and-push:
    name: Build & Push (${{ matrix.variant }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: full
            tl_scheme: full
          - variant: slim
            tl_scheme: small

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Erzeuge Tag-Liste: immer :{variant}, optional zusätzlich :latest
      - name: Compute tags
        id: meta
        run: |
          TAGS="${IMAGE_NAME}:${{ matrix.variant }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ matrix.variant }}" = "${{ env.LATEST_FROM }}" ]; then
            TAGS="$TAGS,${IMAGE_NAME}:latest"
          fi
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

      - name: Build & Push (${{ matrix.variant }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            TL_SCHEME=${{ matrix.tl_scheme }}
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
